services:
  - type: web
    name: stock-prediction-platform
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 5000
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: false
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: stock-prediction-disk
      mountPath: /opt/render/project/data
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
      targetMemoryPercent: 80
